### ISSUE TITLE
Getting "uninitialized constant Spektr::CoreExt::String (NameError)" during GitHub Action/test step

### ISSUE THREAD

**Issue by jasnow** [gregmolnar/spektr#10]
I'm getting the error message below during GitHub Action/test step (not locally).
```
/home/runner/work/feb27/feb27/vendor/bundle/ruby/3.2.0/gems/
zeitwerk-2.6.7/lib/zeitwerk/loader/helpers.rb:135:in `const_get':
uninitialized constant Spektr::CoreExt::String (NameError)
    parent.const_get(cname, false)
          ^^^^^^^^^^
Did you mean?  Strings
               StringIO
               STDIN
```
Here is link to the results of the test step:[GitHub test step](https://github.com/jasnow/feb27/actions/runs/4331461879)

### STEPS TO REPRODUCE
 1. Run "git clone git@github.com:jasnow/feb27.git" .
 2. Run "bundle; rake" with spektr gem in Gemfile commented out. (green)
 3. Uncomment spektr gem in Gemfile and redo step 2. (red)

**Comment by gregmolnar** [comment]
Thanks for reporting it, I fixed it and released 0.4.1 with the fix.

**Comment by jasnow** [comment]
Confirmed

**Comment by gregmolnar** [comment]
Thank you!
