### ISSUE TITLE
No links to this github from the rubygems page

### ISSUE THREAD

**Issue by andynu** [gregmolnar/spektr#4]
Hi looking at the rubygems page

https://rubygems.org/gems/spektr

The homepage points at https://railscop.com/ (does not exist)

And there are no Source Code or Changelog links that direct here.

There should probably be some link back to here from the rubygems page.

Thanks!

**Comment by gregmolnar** [comment]
Thanks for the report. I fixed these in the Gemspec, rubygems will update itself on the next release.
