### ISSUE TITLE
Add batch option

### ISSUE THREAD

**Issue by jasnow** [gregmolnar/spektr#8]
Would be nice to have an minimum batch option, such as "spektr -b",  so you would get no output if no vulnerabilities.

**Comment by jasnow** [comment]
A second way is to send the vulnerabilities to stderr and other stuff to stdout.

**Comment by jasnow** [comment]
Workaround:  spektr 2>&1 |egrep "Name"

**Comment by gregmolnar** [comment]
@jasnow what would be your use case for that? Usually, we rely on return codes and I thought the CLI already handles that, but now I am unsure. I will check that when I work on the gem next time.

**Comment by jasnow** [comment]
Use Case: Inside a shell script - very "Unix" mindset - quiet if "0" else tell me more. I'm all good. 
Ran it on several repos today and found/fixed stuff. Thanks.

**Comment by gregmolnar** [comment]
@jasnow I verified that and I return exit codes based on the findings. I am not a bash wizard,  but I guess you could rely on those. 
The current implementation just puts the data to the console as the script runs, so there is an indication of the script running, so inside the code, it would be challenging to only do this when there are results(we don't know that in advance). I could add a different output formatter though, which would silent output and app details and just out the results if there are any.
